/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/staff/events/global-drop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inspect process-local global drop event (game.event.global-drop capability) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Authoritative World snapshot; event is not resumed after restart */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GlobalDropStatus"];
                    };
                };
                default: components["responses"]["Error"];
            };
        };
        put?: never;
        /** Start or stop global drop through embedded World queue; staff session rechecked at execution */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Token from session endpoint. POST also requires exact Origin and session cookie. */
                    "X-CSRF-Token": components["parameters"]["CSRF"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["GlobalDropCommand"];
                };
            };
            responses: {
                /** @description Domain receipt (code ok means success); retry uncertain outcomes with the identical body and operationId */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GlobalDropResult"];
                    };
                };
                default: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/events/quiz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inspect process-local quiz event (game.event.quiz capability) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Authoritative World snapshot; event is not resumed after restart */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QuizStatus"];
                    };
                };
                default: components["responses"]["Error"];
            };
        };
        put?: never;
        /** Start or stop quiz through embedded World queue; staff session rechecked at execution */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Token from session endpoint. POST also requires exact Origin and session cookie. */
                    "X-CSRF-Token": components["parameters"]["CSRF"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["QuizCommand"];
                };
            };
            responses: {
                /** @description Domain receipt (code ok means success); retry uncertain outcomes with the identical body and operationId */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QuizResult"];
                    };
                };
                default: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get session and CSRF token; create an anonymous session if absent */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current session; never a bearer credential */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Session"];
                    };
                };
                default: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate session after game password, staff allowlist and configured administrative PIN verification */
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Token from session endpoint. POST also requires exact Origin and session cookie. */
                    "X-CSRF-Token": components["parameters"]["CSRF"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        username: string;
                        password: string;
                        adminPin: string;
                    };
                };
            };
            responses: {
                /** @description Authenticated session */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Session"];
                    };
                };
                default: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header: {
                    /** @description Token from session endpoint. POST also requires exact Origin and session cookie. */
                    "X-CSRF-Token": components["parameters"]["CSRF"];
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session invalidated, cookie expired */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @constant */
                            status: "signed_out";
                        };
                    };
                };
                default: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One fresh World snapshot; requires both read capabilities */
        get: {
            parameters: {
                query?: {
                    /** @description Case-insensitive name, account or UID substring; maximum 48 Unicode characters */
                    search?: string;
                    offset?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Snapshot sorted by UID, maximum 50 players; pages are not a stable cursor */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Overview"];
                    };
                };
                default: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/staff/players/{uid}/persistent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read one persisted character projection from PostgreSQL */
        get: {
            parameters: {
                query: {
                    /** @description Account owning the character in the live snapshot */
                    account: string;
                };
                header?: never;
                path: {
                    /** @description Canonical persistent character UID from the live snapshot */
                    uid: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Independent PostgreSQL read; asOf is not the World snapshot timestamp */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PersistentPlayer"];
                    };
                };
                default: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Start requires itemId > 0, ratePercent 1..100 and at least one positive limit. Both limits stop at the first reached. Stop requires an event ID and zero numeric settings. Operation IDs are bound to actor and exact payload, retained up to 1024 commands per process plus one final stop; epoch prevents replay across restarts. */
        GlobalDropCommand: {
            /** @constant */
            version: 1;
            operationId: string;
            epoch: string;
            expectedEventId: string;
            /** @enum {string} */
            action: "start" | "stop";
            reason: string;
            itemId: number;
            ratePercent: number;
            maxDrops: number;
            durationSeconds: number;
        };
        GlobalDropStatus: {
            /** @constant */
            version: 1;
            epoch: string;
            /** Format: date-time */
            asOf: string;
            eventId: string;
            active: boolean;
            itemId: number;
            itemName: string;
            ratePercent: number;
            maxDrops: number;
            dropped: number;
            /** Format: date-time */
            startedAt: string | null;
            /** Format: date-time */
            endsAt: string | null;
            /** @enum {string} */
            endedBy: "" | "time" | "quantity" | "manual";
            actor: string;
        };
        GlobalDropResult: {
            operationId: string;
            /** @enum {string} */
            code: "ok" | "invalid_command" | "capability_required" | "server_maintenance" | "stale_event" | "operation_conflict" | "operation_capacity" | "event_active" | "event_inactive" | "unknown_item" | "event_id_unavailable";
            replayed: boolean;
            status: components["schemas"]["GlobalDropStatus"];
        };
        /** @description Start requires itemId > 0, quantity 1..60 and duration 60..86400 in whole minutes. First round is immediate, then every minute; answers expire after 10 seconds. Stop requires an event ID and zero settings. Retry uncertain outcomes with the identical body; bounded process-local receipts, epoch and event ID prevent replay and stale writes. */
        QuizCommand: {
            /** @constant */
            version: 1;
            operationId: string;
            epoch: string;
            expectedEventId: string;
            /** @enum {string} */
            action: "start" | "stop";
            reason: string;
            itemId: number;
            rewardQuantity: number;
            durationSeconds: number;
        };
        QuizStatus: {
            /** @constant */
            version: 1;
            epoch: string;
            /** Format: date-time */
            asOf: string;
            eventId: string;
            active: boolean;
            itemId: number;
            itemName: string;
            rewardQuantity: number;
            rounds: number;
            correct: number;
            rewarded: number;
            deliveryFailures: number;
            /** Format: date-time */
            startedAt: string | null;
            /** Format: date-time */
            endsAt: string | null;
            /** Format: date-time */
            nextRoundAt: string | null;
            /** Format: date-time */
            roundClosesAt: string | null;
            /** @enum {string} */
            endedBy: "" | "time" | "manual";
            actor: string;
        };
        QuizResult: {
            operationId: string;
            /** @enum {string} */
            code: "ok" | "invalid_command" | "capability_required" | "server_maintenance" | "stale_event" | "operation_conflict" | "operation_capacity" | "event_active" | "event_inactive" | "unknown_item" | "event_id_unavailable";
            replayed: boolean;
            status: components["schemas"]["QuizStatus"];
        };
        Session: {
            authenticated: boolean;
            account: string;
            csrf: string;
            /** Format: date-time */
            expiresAt: string;
        };
        Player: {
            uid: string;
            name: string;
            account: string;
            class: number;
            level: number;
            /** @description Effective live HP from RuntimeScore when present */
            hp: number;
            /** @description Effective live maximum HP */
            maxHp: number;
            /** @description Effective live MP from RuntimeScore when present */
            mp: number;
            /** @description Effective live maximum MP */
            maxMp: number;
            guildId: number;
            guildRank: number;
            /** Format: int64 */
            sessionId: number;
            partySize: number;
            x: number;
            y: number;
        };
        PersistentPlayer: {
            /** @constant */
            version: 1;
            /**
             * Format: date-time
             * @description Timestamp of this PostgreSQL read
             */
            asOf: string;
            account: string;
            uid: string;
            name: string;
            class: number;
            level: number;
            evolution: string;
            /** @description Persisted Score.curHP; not effective live HP */
            hp: number;
            maxHp: number;
            /** @description Persisted Score.curMP; not effective live MP */
            mp: number;
            maxMp: number;
            attack: number;
            magicAttack: number;
            defense: number;
            str: number;
            int: number;
            dex: number;
            con: number;
            statusPoints: number;
            masteryPoints: number;
            skillPoints: number;
            /** @description Persisted character coordinate */
            x: number;
            /** @description Persisted character coordinate */
            y: number;
            gold: number;
            exp: number;
            hold: number;
            cp: number;
        };
        Overview: {
            /** @constant */
            version: 1;
            /** Format: date-time */
            asOf: string;
            /** @enum {string} */
            state: "running" | "maintenance";
            uptimeSeconds: number;
            online: number;
            authenticated: number;
            mobs: number;
            queueDepth: number;
            tickMicros: number;
            lagMicros: number;
            diagnostics: components["schemas"]["Diagnostics"];
            players: components["schemas"]["Player"][];
            matched: number;
            offset: number;
            hasMore: boolean;
        };
        Diagnostics: {
            /** @constant */
            version: 1;
            /**
             * Format: date-time
             * @description Timestamp of process diagnostics
             */
            asOf: string;
            /** Format: int64 */
            postgresQueueDepth: number;
            /** Format: int64 */
            persistenceFailures: number;
            /** Format: int64 */
            panics: number;
        };
    };
    responses: {
        /** @description Rejected request (400/401/403/415), rate limit (429 with Retry-After), or unavailable dependency (503) */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    error: string;
                };
            };
        };
    };
    parameters: {
        /** @description Token from session endpoint. POST also requires exact Origin and session cookie. */
        CSRF: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
