<#
.SYNOPSIS
Checks the single rules file, documentation placement, and reproducible inventory.
#>
[CmdletBinding()]
param([switch]$UpdateMap)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest
$repoRoot = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '../..'))
$mapPath = Join-Path $repoRoot 'DOCS/documentation-map.md'
$issues = [Collections.Generic.List[string]]::new()
$documents = @(Get-ChildItem -LiteralPath $repoRoot -File -Filter '*.md')
foreach ($directory in @('DOCS', '.agents')) {
    $documents += @(Get-ChildItem -LiteralPath (Join-Path $repoRoot $directory) -File -Recurse -Filter '*.md')
}
$documents = @($documents | Sort-Object FullName -Culture en-US)
$obsoletePath = '(?i)(?:clientgo748|(?:client-source|source-client|source-server)[/\\]|CLIENTS[/\\]WYD|(?:wyd-go-feature|wyd-dev-knowledge)[/\\])'
foreach ($directory in @('clientgo748', 'client-source', 'source-client', 'source-server', 'CLIENTS')) {
    if (Test-Path -LiteralPath (Join-Path $repoRoot $directory)) {
        $issues.Add("Obsolete root present: $directory")
    }
}
foreach ($directory in @('tmproject', 'wydgo748', 'references', 'tools', '.github')) {
    foreach ($file in Get-ChildItem -LiteralPath (Join-Path $repoRoot $directory) -Recurse -File -Filter '*.md') {
        # Installed frontend dependencies/builds are generated, not authored source.
        $relativeSource = [IO.Path]::GetRelativePath($repoRoot, $file.FullName).Replace('\', '/')
        if ($relativeSource -match '^wydgo748/web/portal/(node_modules|dist|\.astro)/') { continue }
        $issues.Add("Documentation outside its canonical location: $($file.FullName)")
    }
}
foreach ($file in $documents) {
    if ($file.Name -match '^(AGENTS|CLAUDE)(.*)\.md$' -and $file.FullName -ne (Join-Path $repoRoot 'AGENTS.md')) {
        $issues.Add("Duplicate rules file: $($file.FullName)")
    }
}

$lines = [Collections.Generic.List[string]]::new()
$lines.Add('# Documentation inventory')
$lines.Add('')
$lines.Add('Generated by `tools/repository/Test-RepositoryLayout.ps1 -UpdateMap`.')
$lines.Add('Paths are normalized for the current architecture. Evidence records and handoffs')
$lines.Add('preserve historical validation state; they do not prove current completion.')
$lines.Add('Assets and binary dumps are not documents. Native evidence is in `references/client748/`.')
$lines.Add('')
$lines.Add("Markdown documents: $($documents.Count).")
$lines.Add('')
$lines.Add('| Document | Type |')
$lines.Add('| --- | --- |')
foreach ($file in $documents) {
    $relative = [IO.Path]::GetRelativePath($repoRoot, $file.FullName).Replace('\', '/')
    $target = [IO.Path]::GetRelativePath((Split-Path $mapPath), $file.FullName).Replace('\', '/')
    $kind = if ($relative -like '.agents/skills/*/SKILL.md') { 'Active skill' }
        elseif ($relative -like '.agents/skills/*') { 'Operational reference' }
        elseif ($relative -like '.agents/research/*') { 'Research evidence' }
        elseif ($relative -like '.agents/handoffs/*') { 'Historical continuity' }
        elseif ($relative -eq 'AGENTS.md') { 'Single rules file' }
        else { 'Product documentation' }
    $lines.Add("| [$relative](<$target>) | $kind |")
}
$lines.Add('')
$lines.Add('## Structured research catalogs')
$lines.Add('')
foreach ($file in Get-ChildItem -LiteralPath (Join-Path $repoRoot '.agents/research') -Recurse -File -Filter '*.tsv' | Sort-Object FullName) {
    $relative = [IO.Path]::GetRelativePath($repoRoot, $file.FullName).Replace('\', '/')
    $target = [IO.Path]::GetRelativePath((Split-Path $mapPath), $file.FullName).Replace('\', '/')
    $lines.Add("- [$relative](<$target>)")
}
$expected = ($lines -join "`n") + "`n"
if ($UpdateMap) {
    [IO.File]::WriteAllText($mapPath, $expected, [Text.UTF8Encoding]::new($false))
} elseif (-not (Test-Path -LiteralPath $mapPath) -or [IO.File]::ReadAllText($mapPath).Replace("`r`n", "`n") -cne $expected) {
    $issues.Add('Inventory is outdated; run with -UpdateMap.')
}

# Local inline links: URLs, anchors, and fenced examples are not paths.
foreach ($file in $documents) {
    $body = [IO.File]::ReadAllText($file.FullName)
    if ($body -match $obsoletePath) {
        $issues.Add("Reference to an obsolete project/path: $($file.FullName)")
    }
    $body = [regex]::Replace($body, '(?ms)^```.*?^```[^\r\n]*', '')
    foreach ($match in [regex]::Matches($body, '\[[^\]\r\n]+\]\((?<target><[^>]+>|[^\s)]+)\)')) {
        $target = $match.Groups['target'].Value.Trim('<', '>')
        if ($target -match '^(?:[a-zA-Z][a-zA-Z0-9+.-]*:|#|/)') { continue }
        $target = [Uri]::UnescapeDataString(($target -split '#', 2)[0])
        if (-not $target) { continue }
        $resolved = [IO.Path]::GetFullPath((Join-Path $file.DirectoryName $target))
        if (-not (Test-Path -LiteralPath $resolved)) {
            $issues.Add("Missing link in $([IO.Path]::GetRelativePath($repoRoot, $file.FullName)): $target")
        }
    }
}
if ($issues.Count) { throw ($issues -join "`n") }
Write-Output "Layout and local links OK; $($documents.Count) documents indexed."
